=== astropy/astropy/astropy/io/votable/data/VOTable.dtd
<!-- DOCUMENT TYPE DEFINITION for VOTable = Virtual Observatory Tabular Format
     See History at      http://vizier.u-strasbg.fr/doc/VOTable
     See Discussions at  http://archives.us-vo.org/VOTable
     Reference DTD as    http://us-vo.org/xml/VOTable.dtd
		or at    http://cdsweb.u-strasbg.fr/xml/VOTable.dtd
     XML Schema at       http://us-vo.org/xml/VOTable.xsd
		or at    http://cdsweb.u-strasbg.fr/xml/VOTable.xsd
.Version 1.0 : 15-Apr-2002
-->

<!-- VOTABLE is the root element -->
<!ELEMENT VOTABLE (DESCRIPTION?, DEFINITIONS?, INFO*, RESOURCE*)>
<!ATTLIST VOTABLE
        ID ID #IMPLIED
        version CDATA #IMPLIED
>

<!-- RESOURCEs can contain other RESOURCES,
     together with TABLEs and other stuff -->
<!ELEMENT RESOURCE (DESCRIPTION?, INFO*, COOSYS*, PARAM*, LINK*, 
     TABLE*, RESOURCE*)>
<!ATTLIST RESOURCE
        name CDATA #IMPLIED
        ID ID #IMPLIED
        type (results | meta) "results"
>

<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT DEFINITIONS (COOSYS?, PARAM?)*>

<!-- INFO is a name-value pair -->
<!ELEMENT INFO (#PCDATA)>
<!ATTLIST INFO
        ID ID #IMPLIED
        name CDATA #IMPLIED
        value CDATA #IMPLIED
>

<!-- A PARAM is similar to a FIELD, but it also has a "value attribute -->
<!ELEMENT PARAM (DESCRIPTION?, VALUES?, LINK*)>
<!ATTLIST PARAM
        ID ID #IMPLIED
        unit CDATA #IMPLIED
        datatype (boolean | bit | unsignedByte | short | int | long | char
	| unicodeChar | float | double | floatComplex | doubleComplex) #IMPLIED
        precision CDATA #IMPLIED
        width CDATA #IMPLIED
        ref IDREF #IMPLIED
        name CDATA #IMPLIED
        ucd CDATA #IMPLIED
        value CDATA #IMPLIED
        arraysize CDATA #IMPLIED
>

<!-- A TABLE is a sequence of FIELDS and LINKS and DESCRIPTION,
     possibly followed by a DATA section -->
<!-- ELEMENT TABLE (DESCRIPTION?, LINK*, FIELD*, DATA?) -->
<!ELEMENT TABLE (DESCRIPTION?, FIELD*, LINK*, DATA?)>
<!ATTLIST TABLE
        ID ID #IMPLIED
        name CDATA #IMPLIED
        ref IDREF #IMPLIED
>

<!-- FIELD is the definition of what is in a column of the table -->
<!-- A field may have 2 sets of VALUES: "legfal" and "actual" -->
<!ELEMENT FIELD (DESCRIPTION?, VALUES*, LINK*)>
<!ATTLIST FIELD
        ID ID #IMPLIED
        unit CDATA #IMPLIED
        datatype (boolean | bit | unsignedByte | short | int | long | char
	| unicodeChar | float | double | floatComplex | doubleComplex) #IMPLIED
        precision CDATA #IMPLIED
        width CDATA #IMPLIED
        ref IDREF #IMPLIED
        name CDATA #IMPLIED
        ucd CDATA #IMPLIED
        arraysize CDATA #IMPLIED
        type (hidden | no_query | trigger) #IMPLIED
>

<!-- VALUES expresses the values that can be taken by the data in a column. -->
<!ELEMENT VALUES (MIN?, MAX?, OPTION*)>
<!ATTLIST VALUES
        ID ID #IMPLIED
        type (legal | actual) "legal"
        null CDATA #IMPLIED
        invalid (yes | no) "no"
>
<!ELEMENT MIN (#PCDATA)>
<!ATTLIST MIN
        value CDATA #REQUIRED
        inclusive (yes | no) "yes"
>
<!ELEMENT MAX (#PCDATA)>
<!ATTLIST MAX
        value CDATA #REQUIRED
        inclusive (yes | no) "yes"
>
<!ELEMENT OPTION (OPTION*)>
<!ATTLIST OPTION
        name CDATA #IMPLIED
        value CDATA #REQUIRED
>

<!-- The link is a URL (href) or some other kind of reference (gref). -->
<!ELEMENT LINK (#PCDATA)>
<!ATTLIST LINK
        ID ID #IMPLIED
        content-role (query | hints | doc) #IMPLIED
        content-type CDATA #IMPLIED
        title CDATA #IMPLIED
        value CDATA #IMPLIED
        href CDATA #IMPLIED
        gref CDATA #IMPLIED
        action CDATA #IMPLIED
>

<!-- DATA is the actual table data, in one of three formats -->
<!ELEMENT DATA (TABLEDATA | BINARY | FITS)>

<!-- Pure XML data -->
<!ELEMENT TABLEDATA (TR*)>
<!ELEMENT TR (TD+)>
<!ELEMENT TD (#PCDATA)>
<!ATTLIST TD
        ref IDREF #IMPLIED
>

<!-- FITS file, perhaps with specification of which extension to seek to -->
<!ELEMENT FITS (STREAM)>
<!ATTLIST FITS
        extnum CDATA #IMPLIED
>

<!-- Binary data format -->
<!ELEMENT BINARY (STREAM)>

<!-- Stream can be local or remote, encoded or not -->
<!ELEMENT STREAM (#PCDATA)>
<!ATTLIST STREAM
        type (locator | other) "locator"
        href CDATA #IMPLIED
        actuate (onLoad | onRequest | other | none) "onRequest"
        encoding (gzip | base64 | dynamic | none) "none"
        expires CDATA #IMPLIED
        rights CDATA #IMPLIED
>

<!-- Expresses the coordinate system we are using -->
<!ELEMENT COOSYS (#PCDATA)>
<!ATTLIST COOSYS
        ID ID #IMPLIED
        equinox CDATA #IMPLIED
        epoch CDATA #IMPLIED
        system (eq_FK4 | eq_FK5 | ICRS | ecl_FK4 | ecl_FK5 | galactic
               | supergalactic | xy | barycentric | geo_app) "eq_FK5"
>

=== astropy/astropy/astropy/io/votable/tests/data/regression.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE VOTABLE SYSTEM "http://us-vo.org/xml/VOTable.dtd">
<VOTABLE version="1.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://www.ivoa.net/xml/VOTable/v1.1"
 xmlns="http://www.ivoa.net/xml/VOTable/v1.1">
<DESCRIPTION > <!-- This should get word-wrapped -->
The VOTable format is an XML standard for the interchange of data represented as a set of tables. In this context, a table is an unordered set of rows, each of a uniform format, as specified in the table metadata. Each row in a table is a sequence of table cells, and each of these contains either a primitive data type, or an array of such primitives. VOTable is derived from the Astrores format [1], itself modeled on the FITS Table format [2]; VOTable was designed to be closer to the FITS Binary Table format.
</DESCRIPTION>
<COOSYS ID="J2000" system="eq_FK5" equinox="J2000"/>
<PARAM datatype="float" name="wrong_arraysize" value="0.000000,0.000000" arraysize="0"/>
<PARAM datatype="float" name="INPUT" value="0.000000,0.000000" arraysize="*" unit="km/h" ucd="phys.size;instr.tel">
  <DESCRIPTION>This is the most interesting parameter in the world, and it drinks Dos Equis</DESCRIPTION>
</PARAM>
<INFO ID="QUERY_STATUS" name="QUERY_STATUS" value="OK">This is some information.</INFO>
<RESOURCE type="results">
<DESCRIPTION>
  This is a resource description
</DESCRIPTION>
<PARAM ID="awesome" datatype="float" name="INPUT" value="0.000000,0.000000" arraysize="*" unit="deg"></PARAM>
<PARAM ID="empty_value" arraysize="*" datatype="char" name="empty_value" unit="foo" value="">
  <VALUES>
    <OPTION name="empty_value" value=""/>
    <OPTION value="90prime"/>
  </VALUES>
</PARAM>
<LINK href="http://www.foo.com/" gref="DECPRECATED">
  <DESCRIPTION>Really, this link is totally bogus.</DESCRIPTION>
</LINK>
<TABLE ID="main_table">
<DESCRIPTION>
  This describes the table.
</DESCRIPTION>
<INFO name="Error" ID="ErrorInfo" value="One might expect to find some INFO here, too..."/>
<GROUP>
  <PARAMref ref="awesome"/>
</GROUP>
<PARAM datatype="float" name="INPUT2" value="0.000000,0.000000" arraysize="*" unit="deg">
  <DESCRIPTION>This is the most interesting parameter in the world, and it drinks Dos Equis</DESCRIPTION>
</PARAM>
<FIELD id="string_test" name="string test" datatype="char" arraysize="*"></FIELD>
<FIELD ID="string_test" name="fixed string test" datatype="char" arraysize="10"/>
<FIELD ID="unicode_test" name="unicode_test" datatype="unicodeChar" arraysize="*"/>
<FIELD ID="fixed_unicode_test" name="unicode test" datatype="unicodeString" arraysize="10"/>
<LINK href="http://tabledata.org/"/>
<FIELD ID="string_array_test" name="string array test" datatype="string" arraysize="4*"/>
<FIELD ID="unsignedByte" name="unsignedByte" datatype="unsignedByte"/>
<FIELD ID="short" name="short" datatype="short">
  <VALUES null="-32769"/>
</FIELD>
<FIELD ID="int" name="int" datatype="int" utype="myint">
  <VALUES null="123456789" ID="int_nulls">
    <MIN value="-1000" inclusive="no"/>
    <MAX value="1000" inclusive="yes"/>
    <OPTION name="bogus" value="whatever"/>
  </VALUES>
  <IGNORE_ME/>
</FIELD>
<FIELD ID="long" name="long" datatype="long">
  <LINK href="http://www.long-integers.com/"/>
  <VALUES ref="int_nulls"/>
</FIELD>
<FIELD ID="double" name="double" datatype="double"/>
<FIELD ID="float" name="float" datatype="float">
  <VALUES null=""/>
</FIELD>
<FIELD ID="array" name="array" datatype="long" arraysize="2x2*">
  <VALUES null="-1"/>
</FIELD>
<FIELD ID="bit" name="bit" datatype="bit"/>
<FIELD ID="bitarray" name="bitarray" datatype="bit" arraysize="2x3"/>
<FIELD ID="bitvararray" name="bitvararray" datatype="bit" arraysize="*"/>
<FIELD ID="bitvararray2" name="bitvararray2" datatype="bit" arraysize="2x3x*"/>
<FIELD ID="floatComplex" name="floatComplex" datatype="floatComplex"/>
<FIELD ID="doubleComplex" name="doubleComplex" datatype="doubleComplex"/>
<FIELD ID="doubleComplexArray" name="doubleComplexArray" datatype="doubleComplex" arraysize="*"/>
<FIELD ID="doubleComplexArrayFixed" name="doubleComplexArrayFixed" datatype="doubleComplex" arraysize="2"/>
<FIELD ID="boolean" name="boolean" datatype="boolean"/>
<FIELD ID="booleanArray" name="booleanArray" datatype="boolean" arraysize="4"/>
<FIELD ID="nulls" name="nulls" datatype="int">
  <VALUES null="-9"/>
</FIELD>
<FIELD ID="nulls_array" name="nulls_array" datatype="int" arraysize="2x2">
  <VALUES null="-9"/>
</FIELD>
<FIELD ID="precision1" name="precision1" datatype="double" precision="E3" width="10"/>
<FIELD ID="precision2" name="precision2" datatype="double" precision="F3"/>
<FIELD ID="doublearray" name="doublearray" datatype="double" arraysize="*">
  <VALUES null="-1"/>
</FIELD>
<FIELD ID="bitarray2" name="bitarray2" datatype="bit" arraysize="16"/>
<GROUP>
  <DESCRIPTION>
    This is just a group to make sure we can round-trip them.
  </DESCRIPTION>
  <DESCRIPTION>
    This should warn of a second description.
  </DESCRIPTION>
  <FIELDref ref="boolean"/>
  <GROUP>
    <PARAMref ref="awesome"/>
    <PARAM datatype="float" name="OUTPUT" value="42"/>
  </GROUP>
  <PARAM datatype="float" name="INPUT3" value="0.000000,0.000000" arraysize="*" unit="deg">
    <DESCRIPTION>This is the most interesting parameter in the world, and it drinks Dos Equis</DESCRIPTION>
  </PARAM>
</GROUP>
<DATA>
<TABLEDATA>
<TR>
  <TD>String &amp; test</TD>
  <TD>Fixed string long test</TD> <!-- Should truncate -->
  <TD>Ceçi n'est pas un pipe</TD> <!-- French, n'est-ce pas? -->
  <TD>Ceçi n'est pas un pipe</TD>
  <TD>ab cd</TD>
  <TD>128</TD>
  <TD>4096</TD>
  <TD>268435456</TD>
  <TD>922337203685477</TD>
  <TD>8.9990234375</TD>
  <TD encoding="base64">P4AAAA==</TD>
  <TD>   </TD>
  <TD>1</TD>
  <TD>1 0 1 1 0 1</TD>
  <TD>1 1 1</TD>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD>0 0 0 0</TD>
  <TD>True</TD>
  <TD>True True True True</TD>
  <TD>0</TD>
  <TD/>
  <TD>1.333333333333333333333333333333333</TD>
  <TD>1.333333333333333333333333333333333</TD>
  <TD/>
  <TD>1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0</TD>
</TR>
<TR>
  <TD><![CDATA[String &amp; test]]></TD> <!-- Test that &amp; is treated literally inside CDATA -->
  <TD>0123456789A</TD>
  <TD>வணக்கம்</TD>
  <TD>வணக்கம்</TD>
  <TD>0123456789A</TD>
  <TD>256</TD> <!-- should overflow to 0 -->
  <TD>65536</TD> <!-- should overflow to 0-->
  <TD>2147483647</TD> <!-- overflowing here would raise a Numpy exception -->
  <TD></TD>
  <TD>1.0e-325</TD> <!-- underflow to 0 -->
  <TD>1.0e-46</TD> <!-- underflow to 0 -->
  <TD>42 32, 12 32</TD>
  <TD>0</TD>
  <TD>0 1 0 0 1 1</TD>
  <TD>0 0 0 0 0</TD>
  <TD>0 1 0 0 1 0 1 0 1 0 1 0</TD>
  <TD>0 0</TD>
  <TD>0 0</TD>
  <TD>0 0 0 0</TD>
  <TD>0 -1 -1 -1</TD>
  <TD>FaLsE</TD>
  <TD>true true falSE TRUE</TD>
  <TD>-9</TD>
  <TD>0 1 2 3</TD>
  <TD>1.0</TD>
  <TD>1.0</TD>
  <TD>0 1 Inf -Inf NaN 0 -1</TD>
  <TD/>
</TR>
<TR>
  <TD>XXXX </TD>
  <TD> XXXX </TD> <!-- Shouldn't output extra 0 bytes even though field is wider than string -->
  <TD> XXXX </TD>
  <TD>0123456789A</TD>
  <TD/>
  <TD>-23</TD> <!-- negative, should wrap around to positive -->
  <TD>-4096</TD> <!-- negative, perfectly valid -->
  <TD>-268435456</TD> <!-- negative, perfectly valid -->
  <TD>-1152921504606846976</TD>  <!-- negative, perfectly valid -->
  <TD>1.0E309</TD>
  <TD>1.0E45</TD>
  <TD>12 34 56 78 87 65 43 21</TD>
  <TD>1</TD>
  <TD>1 1 1 0 0 0</TD>
  <TD>1 0 1 0 1</TD>
  <TD>1 1 1 1 1 1</TD>
  <TD>0 -1</TD>
  <TD>0 -1</TD>
  <TD>0 0 0 0</TD>
  <TD>0 0 0 0</TD>
  <TD>true</TD>
  <TD>true True ? true</TD>
  <TD>2</TD>
  <TD>-9 0 -9 1</TD>
  <TD>1e34</TD>
  <TD>1e34</TD>
  <TD/>
  <TD/>
</TR>
<TR>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD>0xff</TD> <!-- hex -->
  <TD>0xffff</TD> <!-- hex - negative value -->
  <TD>0xfffffff</TD>
  <TD>0xfffffffffffffff</TD>
  <TD>NaN</TD>
  <TD>+Inf</TD>
  <TD>NaN, 23</TD>
  <TD>0</TD>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD>NaN Inf</TD>
  <TD/>
  <TD>0 0 0 0</TD>
  <TD>false</TD>
  <TD/>
  <TD/>
  <TD>0 -9 1 -9</TD>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
</TR>
<TR>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD>0x100</TD> <!-- hex, overflow -->
  <TD>0x10000</TD> <!-- hex, overflow -->
  <TD/>
  <TD/>
  <TD>-Inf</TD>
  <TD/>
  <TD>31, -1</TD>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD>0 0 0 0</TD>
  <TD/>
  <TD/>
  <TD>-9</TD>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
</TR>
</TABLEDATA>
</DATA>
</TABLE>
<RESOURCE>
 <TABLE ref="main_table">
   <DESCRIPTION>
     This is a referenced table
   </DESCRIPTION>
   <DATA>
<TABLEDATA>
<TR>
  <TD>String &amp; test</TD>
  <TD>Fixed string long test</TD> <!-- Should truncate -->
  <TD>Ceçi n'est pas un pipe</TD> <!-- French, n'est-ce pas? -->
  <TD>Ceçi n'est pas un pipe</TD>
  <TD>ab cd</TD>
  <TD>128</TD>
  <TD>4096</TD>
  <TD>268435456</TD>
  <TD>922337203685477</TD>
  <TD>8.9990234375</TD>
  <TD encoding="base64">P4AAAA==</TD>
  <TD>   </TD>
  <TD>1</TD>
  <TD>1 0 1 1 0 1</TD>
  <TD>1 1 1</TD>
  <TD/>
  <TD/>
  <TD/>
  <TD/>
  <TD>0 0 0 0</TD>
  <TD>True</TD>
  <TD>True True True True</TD>
  <TD>0</TD>
  <TD/>
  <TD>1.333333333333333333333333333333333</TD>
  <TD>1.333333333333333333333333333333333</TD>
  <TD/>
  <TD>1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0</TD>
</TR>
</TABLEDATA>
</DATA>
</TABLE>
<TABLE ref="main_table" ID="last_table">
<DATA>
<TABLEDATA/> <!-- Add an empty table because it's a useful thing to test -->
</DATA>
</TABLE>
</RESOURCE>
</RESOURCE>
</VOTABLE>

=== astropy/astropy/astropy/ioutils/votable/tests/data/irsa-nph-m31.xml
<?xml version="1.0"?>
<!DOCTYPE VOTABLE SYSTEM "http://us-vo.org/xml/VOTable.dtd">
<VOTABLE version="v1.0">
<DEFINITIONS>
<COOSYS ID="J2000" equinox="2000." epoch="2000." system="eq_FK5" />
</DEFINITIONS>
<RESOURCE>
<PARAM name="fixlen" datatype="char" arraysize="*" value="T" />
<PARAM name="primary" datatype="char" arraysize="*" value="0" />
<PARAM name="RowsRetrieved" datatype="char" arraysize="*" value="18" />
<PARAM name="QueryTime" datatype="char" arraysize="*" value="00:00:00.01625" />
<PARAM name="ORIGIN" datatype="char" arraysize="*" value="&apos;IPAC Infrared Science Archive (IRSA), Caltech/JPL&apos;" />
<PARAM name="DATETIME" datatype="char" arraysize="*" value="&apos;2010-06-16 17:10:01&apos;" />
<PARAM name="DataTag" datatype="char" arraysize="*" value="&apos;ADS/IRSA.Gator#2010/0616/171001_27166&apos;" />
<PARAM name="DATABASE" datatype="char" arraysize="*" value="&apos;2MASS All-Sky Point Source Catalog (PSC) (fp_psc)&apos;" />
<PARAM name="EQUINOX" datatype="char" arraysize="*" value="&apos;J2000&apos;" />
<PARAM name="SKYAREA" datatype="char" arraysize="*" value="&apos;within 10 arcsec of  ra=10.68468 dec=+41.26904 Eq J2000 &apos;" />
<PARAM name="SQL" datatype="char" arraysize="*" value="&apos;WHERE (no constraints)" />
<PARAM name="SQL" datatype="char" arraysize="*" value="&apos;SELECT (19 column names follow in next row.)&apos;" />
<TABLE>
<FIELD name="ra" ucd="POS_EQ_RA_MAIN" ref="J2000" datatype="float" unit="deg" precision="F3" width="7" />
<FIELD name="dec" ucd="POS_EQ_DEC_MAIN" ref="J2000" datatype="float" unit="deg" precision="F3" width="7" />
<FIELD name="clon" datatype="char" arraysize="*"/>
<FIELD name="clat" datatype="char" arraysize="*"/>
<FIELD name="err_maj" datatype="double" unit="arcsec"/>
<FIELD name="err_min" datatype="double" unit="arcsec"/>
<FIELD name="designation" datatype="char" arraysize="*"/>
<FIELD name="j_m" datatype="double" unit="mag"/>
<FIELD name="j_msigcom" datatype="double" unit="mag"/>
<FIELD name="h_m" datatype="double" unit="mag"/>
<FIELD name="h_msigcom" datatype="double" unit="mag"/>
<FIELD name="k_m" datatype="double" unit="mag"/>
<FIELD name="k_msigcom" datatype="double" unit="mag"/>
<FIELD name="ph_qual" datatype="char" arraysize="*"/>
<FIELD name="rd_flg" datatype="char" arraysize="*"/>
<FIELD name="bl_flg" datatype="char" arraysize="*"/>
<FIELD name="cc_flg" datatype="char" arraysize="*"/>
<FIELD name="gal_contam" datatype="int" unit=" "/>
<FIELD name="mp_flg" datatype="int" unit=" "/>
<FIELD name="dist" datatype="double" unit=" "/>
<FIELD name="angle" datatype="double" unit=" "/>
<FIELD name="j_h" datatype="double" unit=" "/>
<FIELD name="h_k" datatype="double" unit=" "/>
<FIELD name="j_k" datatype="double" unit=" "/>
<FIELD name="id" ucd="ID_MAIN" datatype="char" arraysize="*" />
<DATA>
<TABLEDATA>
<TR><TD>10.683263</TD><TD>41.267456</TD><TD>00h42m43.98s</TD><TD>41d16m02.84s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424398+4116028</TD><TD>12.136</TD><TD>0.040</TD><TD>9.226</TD><TD>null</TD><TD>8.994</TD><TD>null</TD><TD>AUU</TD><TD>200</TD><TD>100</TD><TD>c00</TD><TD>2</TD><TD>0</TD><TD>6.871574</TD><TD>213.916</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>0</TD></TR>
<TR><TD>10.682777</TD><TD>41.270111</TD><TD>00h42m43.87s</TD><TD>41d16m12.40s</TD><TD>0.10</TD><TD>0.09</TD><TD>00424386+4116123</TD><TD>9.977</TD><TD>null</TD><TD>11.683</TD><TD>0.056</TD><TD>11.839</TD><TD>0.062</TD><TD>UAA</TD><TD>022</TD><TD>011</TD><TD>0cc</TD><TD>2</TD><TD>0</TD><TD>6.432619</TD><TD>306.825</TD><TD>-</TD><TD>-0.1560</TD><TD>-</TD><TD>1</TD></TR>
<TR><TD>10.684737</TD><TD>41.269035</TD><TD>00h42m44.34s</TD><TD>41d16m08.53s</TD><TD>0.08</TD><TD>0.07</TD><TD>00424433+4116085</TD><TD>9.453</TD><TD>0.052</TD><TD>8.668</TD><TD>0.051</TD><TD>8.475</TD><TD>0.051</TD><TD>EEE</TD><TD>222</TD><TD>111</TD><TD>000</TD><TD>2</TD><TD>0</TD><TD>0.155330</TD><TD>96.656</TD><TD>0.7850</TD><TD>0.1930</TD><TD>0.9780</TD><TD>2</TD></TR>
<TR><TD>10.682383</TD><TD>41.267925</TD><TD>00h42m43.77s</TD><TD>41d16m04.53s</TD><TD>0.10</TD><TD>0.09</TD><TD>00424377+4116045</TD><TD>12.446</TD><TD>0.061</TD><TD>11.753</TD><TD>0.063</TD><TD>9.075</TD><TD>null</TD><TD>AAU</TD><TD>220</TD><TD>110</TD><TD>cc0</TD><TD>2</TD><TD>0</TD><TD>7.398810</TD><TD>237.145</TD><TD>0.6930</TD><TD>-</TD><TD>-</TD><TD>3</TD></TR>
<TR><TD>10.686026</TD><TD>41.269226</TD><TD>00h42m44.65s</TD><TD>41d16m09.21s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424464+4116092</TD><TD>9.299</TD><TD>null</TD><TD>8.606</TD><TD>null</TD><TD>10.119</TD><TD>0.056</TD><TD>UUE</TD><TD>002</TD><TD>001</TD><TD>00c</TD><TD>2</TD><TD>0</TD><TD>3.703143</TD><TD>79.581</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>4</TD></TR>
<TR><TD>10.685657</TD><TD>41.269550</TD><TD>00h42m44.56s</TD><TD>41d16m10.38s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424455+4116103</TD><TD>10.773</TD><TD>0.069</TD><TD>8.532</TD><TD>null</TD><TD>8.254</TD><TD>null</TD><TD>EUU</TD><TD>200</TD><TD>200</TD><TD>c00</TD><TD>2</TD><TD>0</TD><TD>3.218640</TD><TD>55.219</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>5</TD></TR>
<TR><TD>10.684029</TD><TD>41.270901</TD><TD>00h42m44.17s</TD><TD>41d16m15.24s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424416+4116152</TD><TD>10.063</TD><TD>null</TD><TD>9.359</TD><TD>null</TD><TD>11.409</TD><TD>0.055</TD><TD>UUA</TD><TD>002</TD><TD>001</TD><TD>00c</TD><TD>2</TD><TD>0</TD><TD>6.927244</TD><TD>345.269</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>6</TD></TR>
<TR><TD>10.687611</TD><TD>41.270302</TD><TD>00h42m45.03s</TD><TD>41d16m13.09s</TD><TD>0.18</TD><TD>0.14</TD><TD>00424502+4116130</TD><TD>13.055</TD><TD>0.109</TD><TD>9.504</TD><TD>null</TD><TD>9.246</TD><TD>null</TD><TD>AUU</TD><TD>200</TD><TD>200</TD><TD>c00</TD><TD>2</TD><TD>0</TD><TD>9.139894</TD><TD>60.192</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>7</TD></TR>
<TR><TD>10.687414</TD><TD>41.267632</TD><TD>00h42m44.98s</TD><TD>41d16m03.48s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424497+4116034</TD><TD>12.371</TD><TD>0.036</TD><TD>9.627</TD><TD>null</TD><TD>9.379</TD><TD>null</TD><TD>EUU</TD><TD>200</TD><TD>100</TD><TD>c00</TD><TD>2</TD><TD>0</TD><TD>8.967827</TD><TD>124.417</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>8</TD></TR>
<TR><TD>10.684180</TD><TD>41.266941</TD><TD>00h42m44.20s</TD><TD>41d16m00.99s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424420+4116009</TD><TD>10.065</TD><TD>null</TD><TD>9.374</TD><TD>null</TD><TD>11.504</TD><TD>0.052</TD><TD>UUA</TD><TD>002</TD><TD>002</TD><TD>00c</TD><TD>2</TD><TD>0</TD><TD>7.676590</TD><TD>190.151</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>9</TD></TR>
<TR><TD>10.685270</TD><TD>41.267124</TD><TD>00h42m44.46s</TD><TD>41d16m01.65s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424446+4116016</TD><TD>12.070</TD><TD>0.035</TD><TD>9.301</TD><TD>null</TD><TD>9.057</TD><TD>null</TD><TD>EUU</TD><TD>206</TD><TD>200</TD><TD>c00</TD><TD>2</TD><TD>0</TD><TD>7.079993</TD><TD>166.968</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>10</TD></TR>
<TR><TD>10.682713</TD><TD>41.267056</TD><TD>00h42m43.85s</TD><TD>41d16m01.40s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424385+4116014</TD><TD>10.176</TD><TD>null</TD><TD>11.876</TD><TD>0.050</TD><TD>9.252</TD><TD>null</TD><TD>UEU</TD><TD>020</TD><TD>010</TD><TD>0c0</TD><TD>2</TD><TD>0</TD><TD>8.907431</TD><TD>216.693</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>11</TD></TR>
<TR><TD>10.686846</TD><TD>41.270714</TD><TD>00h42m44.84s</TD><TD>41d16m14.57s</TD><TD>0.13</TD><TD>0.11</TD><TD>00424484+4116145</TD><TD>12.872</TD><TD>0.061</TD><TD>9.433</TD><TD>null</TD><TD>9.178</TD><TD>null</TD><TD>AUU</TD><TD>200</TD><TD>200</TD><TD>c00</TD><TD>2</TD><TD>0</TD><TD>8.406324</TD><TD>44.200</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>12</TD></TR>
<TR><TD>10.686015</TD><TD>41.269630</TD><TD>00h42m44.64s</TD><TD>41d16m10.67s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424464+4116106</TD><TD>9.399</TD><TD>null</TD><TD>9.985</TD><TD>0.070</TD><TD>8.429</TD><TD>null</TD><TD>UEU</TD><TD>020</TD><TD>020</TD><TD>0c0</TD><TD>2</TD><TD>0</TD><TD>4.190485</TD><TD>59.544</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>13</TD></TR>
<TR><TD>10.683469</TD><TD>41.268585</TD><TD>00h42m44.03s</TD><TD>41d16m06.91s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424403+4116069</TD><TD>9.321</TD><TD>null</TD><TD>8.614</TD><TD>null</TD><TD>10.601</TD><TD>0.025</TD><TD>UUE</TD><TD>002</TD><TD>001</TD><TD>00c</TD><TD>2</TD><TD>0</TD><TD>3.663337</TD><TD>243.440</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>14</TD></TR>
<TR><TD>10.683944</TD><TD>41.266682</TD><TD>00h42m44.15s</TD><TD>41d16m00.06s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424414+4116000</TD><TD>12.565</TD><TD>0.055</TD><TD>9.510</TD><TD>null</TD><TD>9.274</TD><TD>null</TD><TD>AUU</TD><TD>206</TD><TD>200</TD><TD>c00</TD><TD>2</TD><TD>0</TD><TD>8.719308</TD><TD>193.203</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>15</TD></TR>
<TR><TD>10.685837</TD><TD>41.270599</TD><TD>00h42m44.60s</TD><TD>41d16m14.16s</TD><TD>0.13</TD><TD>0.12</TD><TD>00424460+4116141</TD><TD>9.880</TD><TD>null</TD><TD>12.051</TD><TD>0.068</TD><TD>8.934</TD><TD>null</TD><TD>UAU</TD><TD>020</TD><TD>020</TD><TD>0c0</TD><TD>2</TD><TD>0</TD><TD>6.426487</TD><TD>29.152</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>16</TD></TR>
<TR><TD>10.683465</TD><TD>41.269676</TD><TD>00h42m44.03s</TD><TD>41d16m10.83s</TD><TD>0.13</TD><TD>0.11</TD><TD>00424403+4116108</TD><TD>11.507</TD><TD>0.056</TD><TD>8.744</TD><TD>null</TD><TD>8.489</TD><TD>null</TD><TD>EUU</TD><TD>200</TD><TD>100</TD><TD>c00</TD><TD>2</TD><TD>0</TD><TD>4.006223</TD><TD>304.855</TD><TD>-</TD><TD>-</TD><TD>-</TD><TD>17</TD></TR>
</TABLEDATA>
</DATA>
</TABLE>
</RESOURCE>
</VOTABLE>
